parameters:
    thrift.client.class: Overblog\ThriftBundle\Client\ThriftClient
    thrift.client.test.class: Overblog\ThriftBundle\Client\ThriftTestClient
    thrift.compile_warmer.class: Overblog\ThriftBundle\CacheWarmer\ThriftCompileCacheWarmer
    thrift.factory.class: Overblog\ThriftBundle\Factory\ThriftFactory
    thrift.classloader.listener.class: Overblog\ThriftBundle\Listener\ClassLoaderListener
    thrift.routing.loader.class: Overblog\ThriftBundle\Routing\ThriftRoutingLoader
    thrift.client_cache_proxy_manager: Overblog\ThriftBundle\Cache\ClientCacheProxyManager
    thrift.metadata.class: Overblog\ThriftBundle\Metadata\Metadata
    thrift.cache_dir: "%kernel.cache_dir%/thrift"

services:
    thrift.compile_warmer:
        class: "%thrift.compile_warmer.class%"
        arguments: ["%thrift.cache_dir%", "%kernel.root_dir%", "@thrift.metadata"]

    thrift.factory:
        class: "%thrift.factory.class%"
        arguments: ["@thrift.metadata", "@thrift.client_cache_proxy_manager"]

    thrift.classloader.listener:
        class: "%thrift.classloader.listener.class%"
        arguments: ["%thrift.cache_dir%"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: 255 }

    thrift.routing.loader:
        class: "%thrift.routing.loader.class%"
        arguments: ["@thrift.metadata"]
        tags:
            - { name: routing.loader, priority: 255 }

    thrift.client_cache_proxy_manager:
        class: "%thrift.client_cache_proxy_manager%"
        public: false
        arguments: ["%thrift.cache_dir%/ThriftClientCacheProxy", ~]

    thrift.client.test:
        class: "%thrift.client.test.class%"
        public: false
        parent: thrift.client

    thrift.client:
        class: "%thrift.client.class%"
        public: false
        arguments:
            - "@thrift.factory"
            - ~

    thrift.metadata:
        class: "%thrift.metadata.class%"
        public: false
        arguments:
            - ~
